apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-staging
  template:
    metadata:
      labels:
        app: hello-world-staging
    spec:
      containers:
      - name: hello-world-staging
        image: ghcr.io/jinalbabariya/myapp:ea072188400975e26acfb8b01c888be7caeae63f
        ports:
        - containerPort: 8080
