apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-prod
  template:
    metadata:
      labels:
        app: hello-world-prod
    spec:
      containers:
      - name: hello-world-prod
        image: ghcr.io/jinalbabariya/myapp:4d4d0fcfedd668549fd10be8b3042c1e6192e060
        ports:
        - containerPort: 8080
